### ISSUE TITLE
Please make string escaping optional (i.e. clean_metric_name() should be optional)

### ISSUE THREAD

**Issue by mpenning** [daniellawrence/graphitesend#20]
Thank you for the good work on `graphitesend`!

I have a [small project](https://github.com/mpenning/graphite-gardener) which sends stats to graphite via `send_list(stats_list)`, where `stats_list` is a list of tuples.  The problem is that I'm trying to replace an existing [collectd Write_Graphite plugin](https://collectd.org/wiki/index.php/Plugin:Write_Graphite), and that plugin escapes stats slightly differently than `graphitesend` does.

Of course, I could always just open a tcp socket and dump into graphite, but I'm hoping to use `graphitesend` instead.

I'd like a configurable `auto_escape` option, like this...

```
    gs = graphitesend.init(graphite_server=self.server,
        graphite_port=self.port,
        prefix=self.prefix,
        system_name=self.host.name,
        group='snmp',
        auto_escape=False)
      #^^^^^^^^^^^^^^^^^^^^^^^^^
```

The default for `auto_escape` should be True for backwards compatibility. If `auto_escape` is False, `clean_metric_name()` should never be called on metrics.  That leaves me responsible for escaping characters, which is just fine by me.

I can submit a PR if you like.

**Comment by Shir0kamii** [comment]
Hello,

Today a `clean_metric_name` option is available and allow to do exactly what you need!
