### ISSUE TITLE
import syntax problem

### ISSUE THREAD

**Issue by labrown** [daniellawrence/graphitesend#21]
Greetings,

In both python 2.6.6 on a centos 6 box and in Portal Python 2.7.6 on a Windows computer, I need to do:

    from graphitesend import graphitesend
    gs = graphitesend.init()
    gs.send("foo", 5)

in order for graphitesend to work.  If I just do an import, as per your documentation, I get the following:

    import graphitesend
    gs = graphitesend.init()
    gs.send("foo", 5)

results in:

    $ python t.py 
    Traceback (most recent call last):
      File "t.py", line 2, in <module>
        gs = graphitesend.init()
    AttributeError: 'module' object has no attribute 'init'

**Comment by daniellawrence** [comment]
I dont think I have ever run any of graphitesend on python 2.6.
I'll have a look into the errors for a easy fix.

**Comment by squareatom** [comment]
Same issue with graphitesend 0.4.0 on RHEL 6.5 w/Python 2.6.6
