### ISSUE TITLE
Allow "-" (Dash) in Metric Names

### ISSUE THREAD

**Issue by RonRothman** [daniellawrence/graphitesend#22]
Thanks for a great little project.  We've been using it happily for some time, but it turns out that the metric "cleaning" is getting in our way.

For example, why remove dashes from metric names?  Unlike, say, slashes or parens, I can't see why they'd pose a problem.  (In fact, in our case, _removing_ them is causing us much grief.)

https://github.com/daniellawrence/graphitesend/blob/master/graphitesend/graphitesend.py#L176

Can we relax the metric name cleaning rules, or make it more user-configurable, or remove them all together?

I'm happy to help code this; just let me know.  Thanks!

**Comment by daniellawrence** [comment]
hmmm.

I don't want to change how it works out of the box, else everyone running this will get a brand new set of metrics.

we could add an extra argument say, 'skip_clean_hyphen', defaulted to false
Then only if we skip_clean_hyphen is True we not remove '-' with '_'.

If this was added with a test very similar to https://github.com/daniellawrence/graphitesend/blob/master/tests/test_all.py#L143 and https://github.com/daniellawrence/graphitesend/blob/master/tests/test_all.py#L126.

If you add the extra argument into the README.md and docstrings
https://github.com/daniellawrence/graphitesend/blob/master/graphitesend/graphitesend.py#L42-L43
This way other users will be able to find the new features.

It you want to contribute the code, I would be more then happy to help out.

**Comment by Shir0kamii** [comment]
Why not a function parameter, allowing the user to change the cleaning metrics function ? We could make it default to None and use the given function if available. It would be way more modular than just an option for dashes.

**Comment by Shir0kamii** [comment]
@RonRothman The library changed a lot and today it's much more modular so I think you can easily do what you wanted (If you still need it). I'm closing this issue but feel free to open a new one if you have a specific problem.
