### ISSUE TITLE
minor typo: graphitesnd

### ISSUE THREAD

**Issue by vikram-narayan** [daniellawrence/graphitesend#27]
On http://graphitesend.readthedocs.org/en/latest/index.html#installation, it says "Stable releases of graphitesnd are best installed via pip or easy_install."

**Comment by daniellawrence** [comment]
wow I suck that this.
```
$ grep -r esnd .
docs/index.rst:Stable releases of graphitesnd are best installed via ``pip`` or ``easy_install``.
docs/index.rst:We recommend using the latest stable version of graphitesnd; releases are made often
```

Thanks for the bug report, I'll sort this out now.

**Comment by daniellawrence** [comment]
![isuck](http://www.quickmeme.com/img/35/3502d765ce5788d4a0c6f88ff8ec0d9d65e0473c089e7e9cd429e0bf8e0d1ebf.jpg)

https://github.com/daniellawrence/graphitesend/commit/ed24c211fa3d333c98ff429026160d97005ae3f7 fixes up the issues.
