### ISSUE TITLE
gevent and monkey patch the sockets

### ISSUE THREAD

**Issue by Lujeni** [daniellawrence/graphitesend#43]
Hello,

imho, it's a litle bit fishy to use the monkey patch on sockets.
For example when you import the graphitesend library through a synchronous library, it will break.
Maybe, we need to find an other way to add the async layer.

https://github.com/daniellawrence/graphitesend/blob/master/graphitesend/graphitesend.py#L5

Regard

**Comment by Shir0kamii** [comment]
Hi,

I'm sorry for this use of monkey patch, I did it without knowing that it was a bad practice in a library.

@daniellawrence Would you agree that it should be removed and that it should be written in the doc that asynchronoucity requires `gevent.monkey.patch_socket` ?
