### ISSUE TITLE
EASY: Switch from os.uname()[1] to something else...

### ISSUE THREAD

**Issue by daniellawrence** [daniellawrence/graphitesend#50]
Investigate: Switch from os.uname()[1] to from socket import gethostname
- Needs to return the same results
- If its not the same results, then maybe try os.uname() and if its windows use socket gethostname

**Comment by daniellawrence** [comment]
Raised to seperate issues found in https://github.com/daniellawrence/graphitesend/issues/47

**Comment by systems1** [comment]
testing with python 3.x  on windows 
getting below on windows python 3.x 

graphitesend.graphitesend.GraphiteSendException: Unknown error while trying to s
end data down socket to ('graphite', 2003), error: 'bytes' object has no attribu
te 'encode'

if platform might be better ?
https://github.com/jborg/attic/pull/288
"import platform" near top
"platform = platform.uname()[0]"

**Comment by daniellawrence** [comment]
platform.uname() might be the closest drop in replacement without needing conditional logic.

**Comment by daniellawrence** [comment]
@systems1 - Do you want to submit a patch for this ?

**Comment by Shir0kamii** [comment]
This issue has been implemented, I'm closing it.
