### ISSUE TITLE
AttributeError: 'module' object has no attribute 'init'

### ISSUE THREAD

**Issue by Linux-oiD** [daniellawrence/graphitesend#59]
Trying to use this module on Windows with Python 3.4 and CentOS with Python 3.3:

Python 3.3.3 (default, Mar  9 2016, 14:47:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import graphitesend as gr
> > > g = gr.init()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: 'module' object has no attribute 'init'

Module's dictionary:

> > > print(gr.**dict**)
> > > {'**doc**': None, '**cached**': '/usr/local/lib/python3.3/site-packages/graphitesend/**pycache**/**init**.cpython-33.pyc', '**loader**': <_frozen_importlib.SourceFileLoader object at 0x7fb398ce5550>, '__path__': ['/usr/local/lib/python3.3/site-packages/graphitesend'], '**file**': '/usr/local/lib/python3.3/site-packages/graphitesend/**init**.py', '**name**': 'graphitesend', '**builtins**': {'exec': <built-in function exec>, 'MemoryError': <class 'MemoryError'>, 'id': <built-in function id>, 'callable': <built-in function callable>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'PermissionError': <class 'PermissionError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'Warning': <class 'Warning'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'hasattr': <built-in function hasattr>, 'copyright': Copyright (c) 2001-2013 Python Software Foundation.
> > > All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'int': <class 'int'>, 'ord': <built-in function ord>, 'slice': <class 'slice'>, 'dict': <class 'dict'>, 'SystemError': <class 'SystemError'>, 'min': <built-in function min>, 'TypeError': <class 'TypeError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'bytearray': <class 'bytearray'>, 'IOError': <class 'OSError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, '**name**': 'builtins', 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'complex': <class 'complex'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'super': <class 'super'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'locals': <built-in function locals>, 'help': Type help() for interactive help, or help(object) for help about object., 'next': <built-in function next>, 'all': <built-in function all>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'hex': <built-in function hex>, 'enumerate': <class 'enumerate'>, 'license': Type license() to see the full license text, 'classmethod': <class 'classmethod'>, 'NotImplemented': NotImplemented, '**import**': <built-in function __import__>, 'zip': <class 'zip'>, 'input': <built-in function input>, 'BytesWarning': <class 'BytesWarning'>, 'TimeoutError': <class 'TimeoutError'>, 'delattr': <built-in function delattr>, 'KeyError': <class 'KeyError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'bytes': <class 'bytes'>, 'ProcessLookupError': <class 'ProcessLookupError'>, '**doc**': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents`...' in slices.", '**build_class**': <built-in function __build_class__>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'NameError': <class 'NameError'>, 'property': <class 'property'>, 'memoryview': <class 'memoryview'>, 'len': <built-in function len>, 'FutureWarning': <class 'FutureWarning'>, 'EOFError': <class 'EOFError'>, 'chr': <built-in function chr>, '**debug**': True, 'BufferError': <class 'BufferError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'frozenset': <class 'frozenset'>, 'sum': <built-in function sum>, 'pow': <built-in function pow>, 'compile': <built-in function compile>, 'FloatingPointError': <class 'FloatingPointError'>, 'False': False, 'SystemExit': <class 'SystemExit'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, '**package**': None, 'RuntimeError': <class 'RuntimeError'>, 'ascii': <built-in function ascii>, 'object': <class 'object'>, 'UnicodeError': <class 'UnicodeError'>, 'ImportError': <class 'ImportError'>, 'format': <built-in function format>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, '**loader**': <class '_frozen_importlib.BuiltinImporter'>, 'dir': <built-in function dir>, 'ArithmeticError': <class 'ArithmeticError'>, 'bin': <built-in function bin>, 'float': <class 'float'>, 'BlockingIOError': <class 'BlockingIOError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'tuple': <class 'tuple'>, 'TabError': <class 'TabError'>, 'list': <class 'list'>, 'isinstance': <built-in function isinstance>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'staticmethod': <class 'staticmethod'>, 'AssertionError': <class 'AssertionError'>, 'IndentationError': <class 'IndentationError'>, 'IndexError': <class 'IndexError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'ConnectionError': <class 'ConnectionError'>, 'True': True, 'hash': <built-in function hash>, 'print': <built-in function print>, 'range': <class 'range'>, 'ResourceWarning': <class 'ResourceWarning'>, 'EnvironmentError': <class 'OSError'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'oct': <built-in function oct>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'setattr': <built-in function setattr>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'filter': <class 'filter'>, 'reversed': <class 'reversed'>, 'sorted': <built-in function sorted>, 'UserWarning': <class 'UserWarning'>, 'InterruptedError': <class 'InterruptedError'>, 'open': <built-in function open>, 'FileExistsError': <class 'FileExistsError'>, 'any': <built-in function any>, 'bool': <class 'bool'>, 'ReferenceError': <class 'ReferenceError'>, 'map': <class 'map'>, 'BaseException': <class 'BaseException'>, 'NotImplementedError': <class 'NotImplementedError'>, 'repr': <built-in function repr>, 'OverflowError': <class 'OverflowError'>, 'vars': <built-in function vars>, 'max': <built-in function max>, 'ImportWarning': <class 'ImportWarning'>, 'LookupError': <class 'LookupError'>, 'round': <built-in function round>, 'type': <class 'type'>, 'Exception': <class 'Exception'>, 'Ellipsis': Ellipsis, 'str': <class 'str'>, 'GeneratorExit': <class 'GeneratorExit'>, 'StopIteration': <class 'StopIteration'>, 'None': None, 'ValueError': <class 'ValueError'>, 'abs': <built-in function abs>, 'eval': <built-in function eval>, 'divmod': <built-in function divmod>, 'set': <class 'set'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'OSError': <class 'OSError'>, 'iter': <built-in function iter>, 'issubclass': <built-in function issubclass>}, '**package**': 'graphitesend', '**initializing**': False}

**Comment by benhoyt** [comment]
Yeah, I'm running into this issue too -- it's a Python 3.x problem I believe, and `__init__.py` should be changed to use a relative import like so (note the dot):

    from .graphitesend import *

**Comment by benhoyt** [comment]
@Linux-oiD Okay, I guess this library isn't Python 3 ready yet. When I work around the above, the next error is this:

```
Traceback (most recent call last):
  File "/Users/bhoyt/Envs/scip/lib/python3.5/site-packages/graphitesend/graphitesend.py", line 260, in _dispatch_send
    sending_function(message.encode("ascii"))
  File "/Users/bhoyt/Envs/scip/lib/python3.5/site-packages/graphitesend/graphitesend.py", line 291, in _send
    self.socket.sendall(message.encode("ascii"))
AttributeError: 'bytes' object has no attribute 'encode'
```

What's happening is that it's doing a double-encode: `_dispatch_send()` is calling `message.encode('ascii')`, producing a bytes object, and then `_send()` tries to encode to ASCII again. Which is allowed on Python 2 but fails with the above on Python 3 due to the latter's stricter unicode/bytes handling. Oh well...

**Comment by benhoyt** [comment]
@Linux-oiD FWIW, we ended up writing our own Python 3-ready library to solve this: https://github.com/Jetsetter/graphyte -- it works on Python 2.x and 3.x, and also doesn't use any additional 3rd party libraries (graphitesend requires "gevent" for async usage, graphyte just uses the Python standard "threading" module).

**Comment by Shir0kamii** [comment]
`graphitesend` is now Python3 ready and this problem should be fixed. Feel free to open a new issue if the problem persists.

**Comment by ayaanp-dev** [comment]
Do `pip install pygame` in command line or terminal.  If that doesn't work do `python -m pip install pygame`.  If that doesn't work do `py -m pip install pygame`.
