### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sijis** [daniellawrence/graphitesend#65]
Are there any plans to have a new release (maybe `0.7.1`) that includes the latest python3 fixes?

Thanks.

**Comment by ian-zelikman** [comment]
Bump. Any updates on this?

**Comment by msull** [comment]
A new release would be quite handy-- I just discovered this tool and was attempting to utilize it in my python3 project, but it isn't working. I've published my own dev version off of master which works perfectly to our internal servers, but being able to utilize an official version would be great.

**Comment by daniellawrence** [comment]
Sorry about the delay here.
0.10.0 has been pushed to pypi.

https://github.com/daniellawrence/graphitesend/commit/9f9fe053648adf07b6bcb7eac15d0e4a3014f5b3

**Comment by msull** [comment]
Great, thanks so much!
