### ISSUE TITLE
Multiple instances of graphitesend objects do not create sockets properly

### ISSUE THREAD

**Issue by Penumbra69** [daniellawrence/graphitesend#82]
**Python Version:**
Python 3.6.4  (default, Mar 14 2018, 14:54:19)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin

**GraphiteSend version:**
0.10.0

When attempting to instantiate 2 graphitesend objects, only the 2nd graphitesend instance is usable, the 1st becomes broken by creating the second, and when attempting to send data with emitter #1, the below error is raised:

```
...
  File "/---/py3venv/lib/python3.6/site-packages/graphitesend/graphitesend.py", line 423, in send_list
    return self._dispatch_send(message)
  File "/---/python_venv/py3venv/lib/python3.6/site-packages/graphitesend/graphitesend.py", line 248, in _dispatch_send
    "Socket was not created before send"
graphitesend.graphitesend.GraphiteSendException: Socket was not created before send
```

As hostname / prefix etc. are fixated on __init__ -- we need to create 2 objects to post data to two differently structured trees, thus we need two graphitesend objects.

**Comment by Shir0kamii** [comment]
Sorry for the delay !

Indeed, the `init` function will not work to create two instances working at the same time. I recommend you to directly instantiate `GraphiteClient` objects, or `GraphitePickleClient` if needed.
